version: '3'
services:
  node:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
    - /app/node_modules
    - .:/app
    ports:
      - "8000:8000"
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
  postgres:
    image: 'postgres:latest'
    ports:
      - "8001:5432"