FROM node:8.12.0-alpine

WORKDIR '/app'

# First copy the yarn.lock to install stuff and benefit from the layer cache
COPY package.json .

# Install dependencies
RUN npm install

# Copy the code
COPY . .

# Build the project
RUN npm run build

# Tell docker what to run as default
CMD ["npm", "run", "start:dev"]